#DIR OUT are passed from shell command

LIB_DIR = $(DIR)/libraries
TMP = $(DIR)/tmp
HDR = $(LIB_DIR)/includes.h
EXE = $(TMP)/main
OBJS = $(TMP)/main.o $(TMP)/wiring.o $(TMP)/Wire.o
CC = g++
DEBUG = -g
CFLAGS = -c
LFLAGS = -lrt -lpthread

$(TMP)/main: $(OBJS) $(HDR)
	$(CC) $(LFLAGS) $(OBJS) -o $(TMP)/main
	cp $(TMP)/main $(OUT)

$(TMP)/main.o: $(TMP)/main.cpp $(HDR)
	$(CC) $(CFLAGS) $(TMP)/main.cpp -o $(TMP)/main.o

$(TMP)/wiring.o: $(LIB_DIR)/cores/wiring.cpp $(LIB_DIR)/cores/wiring.h $(HDR)
	$(CC) $(CFLAGS) $(LIB_DIR)/cores/wiring.cpp -o $(TMP)/wiring.o

$(TMP)/Wire.o: $(LIB_DIR)/Wire/Wire.cpp $(LIB_DIR)/Wire/Wire.h $(HDR)
	$(CC) $(CFLAGS) $(LIB_DIR)/Wire/Wire.cpp -o $(TMP)/Wire.o

clean:
	\rm $(TMP)/*.o $(TMP)/main
